const societyData = [

  {
    name: "VIBE",
    council: "Cultural Council",
    description: "VIBE is a dance crew at DTU led by Prof. N S Raghava. The society is dedicated to the art of dance, expressing creativity through various dance forms. They participate in competitions and showcase their talent at events.",
    advisor: "Prof. N S Raghava",
    instagram: "https://www.instagram.com/vibe_dance_crew/",
    image: "/society/VIBE.jpeg",
  },
  {
    name: "PANACHE",
    council: "Cultural Council",
    description: "PANACHE is a cultural society at DTU under the guidance of Mrs. Saroj Bala. The society focuses on bringing style and elegance to campus life through various cultural activities and events.",
    advisor: "Mrs Saroj Bala",
    instagram: "https://www.instagram.com/panachedaily/",
    image: "/society/PANACHE.jpeg",
  },
  {
    name: "BHANGRA",
    council: "Cultural Council",
    description: "BHANGRA is a lively and energetic society at DTU that celebrates the rich cultural heritage of Bhangra dance. The society, known for its vibrant performances, invites students to join and experience the joy of Bhangra.",
    advisor: null,
    instagram: "https://www.instagram.com/dtubhangra/",
    image: null,
  },
  {
    name: "PARCHHAYI",
    council: "Cultural Council",
    description: "PARCHHAYI is a society at DTU led by Prof. Rajesh Rohilla. The society is dedicated to showcasing the artistic expressions and talents of the students through various cultural and artistic events.",
    advisor: "Prof. Rajesh Rohilla",
    instagram: "https://www.instagram.com/parchhayi.dtu/",
    image: "/society/PARCHHAYI.jpg",
  },
    {
    name: "PRATIBIMB",
    council: "Cultural Council",
    description: "PRATIBIMB is a cultural society that aims to capture and reflect the vibrant spirit of DTU through various creative endeavors. Under the guidance of Mrs. Saroj Bala, the society engages in diverse cultural activities and events.",
    advisor: "Mrs Saroj Bala",
    instagram: "https://www.instagram.com/pratibimb.dtu/",
    image: "/society/PRATIBIMB.png",
  },
  {
    name: "NRITYANGANA",
    council: "Cultural Council",
    description: "NRITYANGANA is a dance society at DTU led by Dr. Rachna Garg. The society is dedicated to the art of dance, bringing together students with a passion for dance to express themselves and showcase their talent.",
    advisor: "Dr. Rachna Garg",
    instagram: "https://www.instagram.com/dtunrityangana/",
    image: null,
  },
  {
    name: "MADHURIMA",
    council: "Cultural Council",
    description: "MADHURIMA is the music society at DTU, guided by Dr. Richa Srivastava. The society is dedicated to promoting and celebrating music in all its forms, providing a platform for musicians and music enthusiasts.",
    advisor: "Dr. Richa Srivastava",
    instagram: "https://www.instagram.com/madhurima.dtu/",
    image: "/society/MADHURIMA.jpeg",
  },
  {
    name: "KALAKRITI",
    council: "Cultural Council",
    description: "KALAKRITI is a society at DTU led by Mr. Rooplal Rana. The society is dedicated to promoting various forms of art, providing a platform for students to showcase their artistic talents and creativity.",
    advisor: "Mr. Rooplal Rana",
    instagram: "https://www.instagram.com/kalakriti_dtu/",
    image: null,
  },
  {
    name: "YUVAAN",
    council: "Literary Council",
    description: "YUVAAN is a society at DTU that promotes youth engagement and activities. While specific details are not provided, you can connect with them on Instagram to stay updated on their events and initiatives.",
    advisor: null,
    instagram: "https://www.instagram.com/yuvaandtu",
    image: "/society/YUVAAN.webp",
  },
  {
    name: "SAHITYA",
    council: "Literary Council",
    description: "SAHITYA is a literary society at DTU led by Dr. Yogita Kalra. The society focuses on promoting literature and creative writing. Students can participate in various literary events and activities.",
    advisor: "Dr. Yogita Kalra",
    instagram: "https://www.instagram.com/sahitya_dtu/",
    image: "/society/SAHITYA.webp",
  },
  {
    name: "COGNITIVE MINDS",
    council: "Literary Council",
    description: "COGNITIVE MINDS is a society at DTU guided by Ms. Meha Joshi. The society focuses on exploring and understanding cognitive sciences through various activities and discussions.",
    advisor: "Ms. Meha Joshi",
    instagram: "https://www.instagram.com/cognitive_minds_dtu/",
    image: "/society/COGNITIVE MINDS.jpeg",
  },
  {
    name: "TOAST MASTERS",
    council: "Literary Council",
    description: "TOAST MASTERS is a society at DTU that focuses on enhancing public speaking and leadership skills. Under the guidance of Prof. A.K Agarwal, members engage in various activities and workshops.",
    advisor: "Prof. A.K Agarwal",
    instagram: null,
    image: "/society/TOASTMASTERS.jpg",
  },
  {
    name: "DMBS-DTU",
    council: "Literary Council",
    description: "DELTECH MUN & DEBATING SOCIETY, under the guidance of Prof. Nao Kant Deo, is dedicated to Model United Nations and debating activities. Connect with them on Instagram for updates.",
    advisor: "Prof. Nao Kant Deo",
    instagram: "https://www.instagram.com/deltechdebsoc/",
    image: "/society/DBMS-DTU.jpeg",
  },
  {
    name: "QUIZ CLUB",
    council: "Literary Council",
    description: "QUIZ CLUB, led by Dr. Mini Sreejeth, engages students in stimulating quiz competitions and activities. Follow them on Instagram to stay informed about upcoming quiz events.",
    advisor: "Dr. Mini Sreejeth",
    instagram: "https://www.instagram.com/delhi42dtu/",
    image: "/society/DELHI-42.webp",
  },
  {
    name: "ROUND TABLE",
    council: "Literary Council",
    description: "ROUND TABLE is a society at DTU led by Mr. Anurag Chauhan. The society focuses on organizing discussions and events covering a wide range of topics. Stay updated on their activities through Instagram.",
    advisor: "Mr. Anurag Chauhan",
    instagram: "https://www.instagram.com/roundtable_dtu/",
    image: "/society/ROUNDTABLE.jpeg",
  },
  {
    name: "E-CELL",
    council: "Literary Council",
    description: "E-CELL is an entrepreneurial society at DTU guided by Prof. M.M. Tripathi. The society encourages and supports students interested in entrepreneurship. Follow them on Instagram for updates.",
    advisor: "Prof. M.M. Tripathi",
    instagram: "https://www.instagram.com/ecelldtu/",
    image: "/society/E-CELL.png",
  },
  {
    name: "IOSD-DTU",
    council: "Technical Council",
    description: "IOSD-DTU is the Institute of Open Source Developers at DTU, advised by Dr. S M Pandey. While specific details are not provided, you can visit their GitHub profile for more information.",
    advisor: "Dr. S M Pandey",
    instagram: null,
    image: "/society/IOSD-DTU.png",
  },
  {
    name: "ASSETS",
    council: "Technical Council",
    description: "ASSETS, advised by Dr. Archana Singh, focuses on advancing technology in the field of electronics and communication. Follow their Instagram for updates on projects and activities.",
    advisor: "Dr. Archana Singh",
    instagram: "https://www.instagram.com/assets_dtu/",
    image: "/society/ASSETS.jpeg",
  },
  {
    name: "MACS-DTU",
    council: "Technical Council",
    description: "MACS-DTU, advised by Dr. Nilam, is the Mobile and Communication Society at DTU. Stay updated on their projects and events by following them on Instagram.",
    advisor: "Dr. Nilam",
    instagram: "https://www.instagram.com/macs_dtu/",
    image: "/society/MACS-DTU.png",
  },
  {
    name: "SME-DTU",
    council: "Technical Council",
    description: "SME-DTU, advised by Prof. Qasim Murtaza, is the Society of Mechanical Engineers at DTU. Follow their Instagram for updates on mechanical engineering-related activities.",
    advisor: "Prof. Qasim Murtaza",
    instagram: "https://www.instagram.com/dtusme/",
    image: "/society/SME-DTU.jpg",
  },
  {
    name: "ASME-DTU",
    council: "Technical Council",
    description: "ASME-DTU, advised by Prof. Raj Kumar Singh, is the American Society of Mechanical Engineers at DTU. Follow them on Instagram for updates on mechanical engineering events.",
    advisor: "Prof. Raj Kumar Singh",
    instagram: "https://www.instagram.com/asme_dtu/",
    image: "/society/ASME-DTU.jpeg",
  },
  {
    name: "TEDX DTU",
    council: "Technical Council",
    description: "TEDX DTU is the TEDx chapter at DTU. While the advisor is not specified, you can follow them on Instagram for updates on TEDx events and talks.",
    advisor: null,
    instagram: "https://www.instagram.com/tedxdtu/",
    image: "/society/TEDX DTU.jpeg",
  },
  {
    name: "SAE-DTU",
    council: "Technical Council",
    description: "SAE-DTU, advised by Mr. Amit Pal, is the Society of Automotive Engineers at DTU. Follow their Instagram for updates on automotive engineering activities.",
    advisor: "Mr. Amit Pal",
    instagram: "https://www.instagram.com/dtusae/",
    image: "/society/SAE-DTU.jpeg",
  },
  {
    name: "DEPTH-DTU",
    council: "Technical Council",
    description: "DEPTH-DTU, advised by Mr. Deshraj Meena, is the society that organizes the annual tech fest at DTU. Follow them on Instagram for updates on tech events and projects.",
    advisor: "Mr. Deshraj Meena",
    instagram: "https://www.instagram.com/depth_dtu/",
    image: "/society/DEPTH-DTU.jpeg",
  },
  {
    name: "ZENITH",
    council: "Technical Council",
    description: "ZENITH, advised by Dr. Kongan Aryan, is a society at DTU. While specific details are not provided, you can check their LinkedIn for more information.",
    advisor: "Dr. Kongan Aryan",
    instagram: null,
    image: "/society/ZENITH.jpeg",
  },
  {
    name: "SAIM- DTU",
    council: "Technical Council",
    description: "",
    advisor: "Dr. Vivesk Kumar Agarwal",
    instagram: null,
    image: "/society/SAIMDTU.jpeg",
  },
  {
    name: "IICHE",
    council: "Technical Council",
    description: "",
    advisor: "Mr. Manish Jain",
    instagram: "https://www.instagram.com/iichedtu/",
    image: "/society/IICHE.jpeg",
  },
  {
    name: "SCEE",
    council: "Technical Council",
    description: "",
    advisor: "Dr. A.K Shrivasta",
    instagram: "https://www.instagram.com/sceedtu/",
    image: "/society/SCEE.jpeg",
  },
  {
    name: "IEEE",
    council: "Technical Council",
    description: "",
    advisor: "Prof. J.Panda",
    instagram: "https://www.instagram.com/ieee.dtu/",
    image: null,
  },
  {
    name: "COSMOLOGY CLUB",
    council: "Technical Council",
    description: "",
    advisor: "Dr. Rinku Sharma",
    instagram: "https://www.instagram.com/cosmologyclub.dtu/",
    image: "/society/COSMOLOGY CLUB.jpeg",
  },
  {
    name: "SITE",
    council: "Technical Council",
    description: "",
    advisor: null,
    instagram: "https://www.instagram.com/site.dtu/",
    image: "/society/SITE.jpg",
  },
  {
    name: "BIOSOC-DTU",
    council: "Technical Council",
    description: "",
    advisor: "Dr. Yasha Hasija",
    instagram: "https://www.instagram.com/biosocdtu/",
    image: "/society/BIOSOC-DTU.jpeg",
  },
  {
    name: "TEAM INFERNO",
    council: "Innovation Team",
    description: "Team Inferno is dedicated to innovation and robotics. Led by Prof. P.K Jain, they strive to excel in competitive robotics events.",
    advisor: "Prof. P.K Jain",
    instagram: "https://www.instagram.com/inferno.dtu/",
    image: "/society/TEAM INFERNO.jpeg",
  },
  {
    name: "TEAM SUPER MILEAGE",
    council: "Innovation Team",
    description: "Team Super Mileage is committed to designing fuel-efficient vehicles. Under the guidance of Prof. A.K Aggarwal, they participate in competitions focusing on maximum mileage.",
    advisor: "Prof. A.K Aggarwal",
    instagram: "https://www.instagram.com/dtusmv/",
    image: "/society/TEAM SUPER MILEAGE.jpeg",
  },
  {
    name: "DELTECH BAJA",
    council: "Innovation Team",
    description: "Deltech Baja specializes in the design and construction of off-road vehicles. Under the guidance of Prof. M.M Tripathi, they compete in Baja SAE events.",
    advisor: "Prof. M.M Tripathi",
    instagram: "https://www.instagram.com/deltechbaja/",
    image: "/society/DELTECH RAJA.jpeg",
  },
  {
    name: "DEFIANZ RACING TEAM",
    council: "Innovation Team",
    description: "Defianz Racing Team is dedicated to pushing the limits of electric vehicle technology. Under the guidance of Prof. Qasim Mortaza, they participate in competitions focusing on electric racing.",
    advisor: "Prof. Qasim Mortaza",
    instagram: "https://www.instagram.com/teamdefianzracing_dtusdc/",
    image: "/society/DEFIANZ RACING.jpeg",
  },
  {
    name: "UAS-DTU",
    council: "Innovation Team",
    description: "The Unmanned Aerial Systems (UAS) team at DTU focuses on the development and application of drone technology. Guided by Prof. N S Raghava, they explore the capabilities of unmanned flight.",
    advisor: "Prof. N S Raghava",
    instagram: "https://www.instagram.com/uas_dtu/",
    image: "/society/UAS-DTU.png",
  },
  {
    name: "TEAM RAFTAAR",
    council: "Innovation Team",
    description: "Team Raftaar focuses on building high-speed vehicles and participating in racing competitions. Led by Prof. Rajesh Kumar, they aim for speed and precision.",
    advisor: "Prof. Rajesh Kumar",
    instagram: "https://www.instagram.com/teamraftaardtu/",
    image: null,
  },
  {
    name: "Social Societies",
    council: "Social Societies",
    description: "",
    advisor: null,
    instagram: null,
    image: null,
  },
  {
    name: "NSS",
    council: "Social Societies",
    description: "National Service Scheme (NSS) at DTU, guided by Prof. Noakant Deo, is committed to community service and social development.",
    advisor: "Prof. Noakant Deo",
    instagram: "https://www.instagram.com/nssdtu/",
    image: "/society/NSS.jpeg",
  },
  {
    name: "ENACTUS",
    council: "Social Societies",
    description: "ENACTUS DTU, led by Dr. Ruchika Malhotra, focuses on entrepreneurial action for community impact.",
    advisor: "Dr. Ruchika Malhotra",
    instagram: "https://www.instagram.com/enactus_dtu/",
    image: "/society/ENACTUS.jpeg",
  },
  {
    name: "ELIXIR",
    council: "Social Societies",
    description: "ELIXIR, under the guidance of Dr. T Vijay Kumar, explores the realms of chemistry.",
    advisor: "Dr. T Vijay Kumar",
    instagram: "https://www.instagram.com/elixir_dtu/",
    image: "/society/ELIXIR.png",
  },
  {
    name: "ROTARACT CLUB OF DTU",
    council: "Social Societies",
    description: "ROTARACT CLUB OF DTU, advised by Prof. Naokant Deo, is dedicated to community service and leadership development.",
    advisor: "Prof. Naokant Deo",
    instagram: "https://www.instagram.com/rotaractclubdtu/",
    image: "/society/ROTARACT CLUB.jpeg",
  },
  {
    name: "LET'S TALK",
    council: "Social Societies",
    description: "LET'S TALK, guided by Dr. Nand Kumar, is a platform for open conversations and discussions.",
    advisor: "Dr. Nand Kumar",
    instagram: "https://www.instagram.com/letstalk_dtu/",
    image: "/society/LET'S TALK.jpeg",
  },
];

export default societyData;